version: 2.1
jobs:
  test:
    docker:
      - image: groupbyinc/circleci-node:1.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install app dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm test
  deploy_dev:
    docker:
      - image: groupbyinc/circleci-node:1.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install app dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: ./scripts/deploy_dev.sh
  deploy_prod:
    docker:
      - image: groupbyinc/circleci-node:1.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install app dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: ./scripts/deploy_prod.sh
workflows:
  version: 2.1
  test_and_deploy:
    jobs:
      - test
      - deploy_dev:
          filters:
            branches:
              only:
                - develop
          requires:
            - test
      - deploy_prod:
          filters:
            branches:
              only:
                - production
          requires:
            - test
