apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: recommendations-ref-ui
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: recommendations-ref-ui
    spec:
      containers:
      - name: recommendations-ref-ui
        image: groupbyinc/recommendations-ref-ui:3.4.1
        imagePullPolicy: Always
        ports:
          - containerPort: 3000